-- Estrutura do Crivo. SQL portável entre H2 (desenvolvimento e testes) e PostgreSQL.

CREATE TABLE vaga (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo        VARCHAR(80)   NOT NULL,
    area          VARCHAR(40)   NOT NULL,
    descricao     VARCHAR(500),
    salario_base  NUMERIC(12,2) NOT NULL,
    quantidade    INTEGER       NOT NULL,
    status        VARCHAR(10)   NOT NULL,
    criada_em     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    encerrada_em  TIMESTAMP(6) WITH TIME ZONE,
    versao        BIGINT        NOT NULL
);

CREATE TABLE candidato (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vaga_id             BIGINT        NOT NULL,
    nome                VARCHAR(80)   NOT NULL,
    email               VARCHAR(120)  NOT NULL,
    telefone            VARCHAR(20),
    salario_pretendido  NUMERIC(12,2) NOT NULL,
    etapa               VARCHAR(15)   NOT NULL,
    tentativas_contato  INTEGER       NOT NULL,
    inscrito_em         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    atualizado_em       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    versao              BIGINT        NOT NULL,
    CONSTRAINT fk_candidato_vaga FOREIGN KEY (vaga_id) REFERENCES vaga (id),
    CONSTRAINT uk_candidato_vaga_email UNIQUE (vaga_id, email)
);
CREATE INDEX ix_candidato_vaga_etapa ON candidato (vaga_id, etapa);

CREATE TABLE evento (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidato_id    BIGINT       NOT NULL,
    data_hora       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    tipo            VARCHAR(20)  NOT NULL,
    descricao       VARCHAR(200) NOT NULL,
    etapa_anterior  VARCHAR(15),
    etapa_nova      VARCHAR(15),
    CONSTRAINT fk_evento_candidato FOREIGN KEY (candidato_id) REFERENCES candidato (id)
);
CREATE INDEX ix_evento_candidato ON evento (candidato_id, data_hora);
